"""Seed data for packages — used on initial deploy.
Mirrors /app/frontend/src/data/content.js + packageDetails.js so DB is the source of truth after seed.
"""
SEED_PACKAGES = [
    {
        "id": "umrah-economy",
        "name": "Umroh Ekonomi",
        "fullTitle": "Umroh Ekonomi Februari 2026 9 Hari [start Batam]",
        "subtitle": "Classic Bulan Februari 2026 - Program 9 Hari [start Batam]",
        "headline": "BATAM - JAKARTA - JEDDAH | JEDDAH - JAKARTA - BATAM",
        "badge": "Best Value",
        "badgeLong": "PESAWAT GARUDA INDONESIA",
        "duration": "9 Days",
        "durasi": "9 Hari",
        "tipePaket": "Umroh",
        "departures": "Bulanan • Jan – Dec 2026",
        "departureDate": "2026-02-10",
        "returnDate": "2026-02-18",
        "departureCity": "Batam",
        "availableSeats": 35,
        "priceFrom": "Rp 28,900,000",
        "airline": "Garuda Indonesia",
        "hotelMakkah": "Hotel ★★★★ — 700m from Masjidil Haram",
        "hotelMadinah": "Hotel ★★★★ — 300m from Masjid Nabawi",
        "image": "https://images.unsplash.com/photo-1704104501136-8f35402af395?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDk1Nzd8MHwxfHNlYXJjaHw0fHxrYWFiYSUyMG1lY2NhfGVufDB8fHx8MTc4MDE4MjY2NHww&ixlib=rb-4.1.0&q=85",
        "gallery": [
            "https://images.unsplash.com/photo-1704104501136-8f35402af395?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
            "https://images.pexels.com/photos/34498854/pexels-photo-34498854.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=900&w=1200",
            "https://images.pexels.com/photos/18360295/pexels-photo-18360295.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=900&w=1200",
            "https://images.pexels.com/photos/8059446/pexels-photo-8059446.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=900&w=1200",
        ],
        "overview": "Paket Umroh Ekonomi 9 hari dirancang untuk jamaah yang menginginkan pelayanan berkualitas dengan harga terjangkau. Akomodasi nyaman di hotel bintang 4 dengan jarak strategis dari haram, didampingi muthawif berpengalaman.",
        "routes": [
            "Keberangkatan tanggal: 10 Februari 2026",
            "Kepulangan tanggal: 18 Februari 2026",
            "Penerbangan PP Jakarta - Jeddah",
            "Termasuk PP penerbangan domestik Batam - Jakarta",
            "Hotel Madinah Bintang 4 - Qasr Al Ansar Golden Tulip",
            "Hotel Mekkah Bintang 4 - Royal Majestic",
            "Tanpa biaya tambahan",
        ],
        "bonuses": [
            {"title": "BONUS: Kereta Cepat Haramain", "desc": "Madinah ke Mekkah hanya 2 jam dengan kereta cepat berkecepatan 300km/jam.", "image": "https://images.unsplash.com/photo-1581365365829-9c8a64a307c0?auto=format&fit=crop&w=600&q=80"},
        ],
        "pembimbing": "Ustadz alumni Universitas Madinah / Al-Azhar Kairo",
        "highlights": ["ALL-IN Tanpa biaya tambahan", "Hotel Bintang 4 Mekkah & Madinah", "Digital Radio Transmitter per Jamaah", "Handling lengkap di Bandara & Hotel", "Catering Indonesia 3x sehari", "Perlengkapan eksklusif"],
        "includes": ["Tiket pesawat PP (Jakarta/Batam)", "Hotel bintang 4 di Makkah & Madinah", "Visa umroh resmi", "Manasik & bimbingan ibadah", "Muthawif berbahasa Indonesia", "Perlengkapan eksklusif", "Asuransi perjalanan", "Bagasi 30 kg + Zamzam 5L"],
        "excludes": ["Biaya pengurusan paspor & vaksin", "Kelebihan bagasi", "Biaya pribadi", "Tip muthawif & supir (suggested)"],
        "terms": ["Paspor Asli minimal 7 bulan sebelum keberangkatan", "Pas Foto Background Putih 4x6 (80% tampak muka)", "Foto KTP", "Foto Kartu Keluarga (KK)", "Foto Akta Lahir (khusus anak)", "DP Rp 5.000.000 per orang", "Buku Vaksin Meningitis"],
        "hotels": [
            {"name": "Qasr Al Ansar Golden Tulip", "rating": 4, "location": "Madinah", "description": "Hotel premium di Markaziah Madinah, ±4 menit berjalan kaki ke pelataran Masjid Nabawi.", "checkIn": "11 Februari 2026, 16:00", "checkOut": "14 Februari 2026, 13:00", "image": "https://cdn.muslimpergi.com/uploads/hotel/photo/636/medium_qasr-al-ansar-new-palace.jpg"},
            {"name": "Royal Majestic Hotel Makkah", "rating": 4, "location": "Makkah", "description": "Hotel 4 menit dari Abraj Al Bait, ±400m dari Menara Safwah.", "checkIn": "14 Februari 2026, 16:00", "checkOut": "17 Februari 2026, 13:00", "image": "https://cdn.muslimpergi.com/uploads/hotel/photo/175/medium_hotel-royal-majestic-makkah.jpg"},
        ],
        "flights": [
            {"type": "Departure", "airline": "Garuda Indonesia", "logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Garuda_Indonesia_Logo.svg/2560px-Garuda_Indonesia_Logo.svg.png", "from": {"code": "CGK", "name": "Soekarno-Hatta International Airport", "city": "Jakarta, ID"}, "to": {"code": "JED", "name": "King Abdulaziz International Airport", "city": "Jeddah, SA"}, "departTime": "10 Februari 2026, 22:30", "arriveTime": "11 Februari 2026, 06:40"},
            {"type": "Arrival", "airline": "Garuda Indonesia", "logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Garuda_Indonesia_Logo.svg/2560px-Garuda_Indonesia_Logo.svg.png", "from": {"code": "JED", "name": "King Abdulaziz International Airport", "city": "Jeddah, SA"}, "to": {"code": "CGK", "name": "Soekarno-Hatta International Airport", "city": "Jakarta, ID"}, "departTime": "18 Februari 2026, 01:15", "arriveTime": "18 Februari 2026, 17:45"},
        ],
        "transports": [
            {"name": "Dallah Executive Bus", "logo": "https://cdn.muslimpergi.com/uploads/transport/logo/6/medium_dalah.jpg"},
            {"name": "Kereta Cepat Haramain", "logo": "https://cdn.muslimpergi.com/uploads/transport/logo/45/medium_kereta-cepat-mekkah-madinah.jpg"},
        ],
        "itinerary": [
            {"day": 1, "date": "10 Februari 2026", "dayName": "Selasa", "title": "BATAM - JAKARTA - JEDDAH", "meals": "Makan Malam (Bandara)", "activities": ["Sore hari Jamaah berkumpul di Bandara Hang Nadim Batam.", "Penerbangan Batam - Jakarta, transit untuk keberangkatan internasional.", "Boarding Garuda Indonesia menuju Jeddah."]},
            {"day": 2, "date": "11 Februari 2026", "dayName": "Rabu", "title": "JEDDAH - MADINAH", "meals": "Sarapan (Pesawat), Makan Siang (Bus), Makan Malam (Hotel)", "activities": ["Tiba di Bandara King Abdul Aziz Jeddah, proses Imigrasi.", "Perjalanan menuju Madinah dengan bus eksekutif.", "Check-in hotel, istirahat, ibadah di Masjid Nabawi."]},
            {"day": 3, "date": "12 Februari 2026", "dayName": "Kamis", "title": "MADINAH", "meals": "Sarapan, Makan Siang, Makan Malam (Hotel)", "activities": ["Sholat Subuh berjamaah di Masjid Nabawi.", "Walking tour area Nabawi, ziarah Makam Rasulullah SAW & Baqi.", "Memperbanyak ibadah."]},
            {"day": 4, "date": "13 Februari 2026", "dayName": "Jumat", "title": "ZIARAH MADINAH", "meals": "Sarapan, Makan Siang, Makan Malam (Hotel)", "activities": ["Ziarah Masjid Quba, Jabal Uhud, Masjid Qiblatain, Pasar Kurma.", "Sholat Jumat berjamaah.", "Ziarah Raudhah (sesuai tasreh)."]},
            {"day": 5, "date": "14 Februari 2026", "dayName": "Sabtu", "title": "MADINAH - MAKKAH", "meals": "Sarapan, Makan Siang, Makan Malam (Hotel)", "activities": ["Check-out hotel Madinah, miqot di Bir Ali.", "Kereta Cepat Haramain ke Makkah.", "Umroh I: Tawaf - Sai - Tahallul."]},
            {"day": 6, "date": "15 Februari 2026", "dayName": "Ahad", "title": "MAKKAH (City Tour)", "meals": "Sarapan, Makan Siang, Makan Malam (Hotel)", "activities": ["Sholat Subuh di Masjidil Haram.", "City tour: Jabal Tsur, Arafah, Muzdalifah, Mina, Jabal Nur.", "Miqot di Tan'im untuk Umroh II."]},
            {"day": 7, "date": "16 Februari 2026", "dayName": "Senin", "title": "IBADAH DI MAKKAH", "meals": "Sarapan, Makan Siang, Makan Malam (Hotel)", "activities": ["Memperbanyak ibadah (acara bebas).", "Sholat 5 waktu berjamaah."]},
            {"day": 8, "date": "17 Februari 2026", "dayName": "Selasa", "title": "MAKKAH - JEDDAH - JAKARTA", "meals": "Sarapan (Hotel), Makan Malam (Pesawat)", "activities": ["Tawaf Wada' (perpisahan), check-out.", "Perjalanan ke Bandara Jeddah.", "Penerbangan Jeddah - Jakarta."]},
            {"day": 9, "date": "18 Februari 2026", "dayName": "Rabu", "title": "JAKARTA - BATAM", "meals": "Sarapan (Pesawat)", "activities": ["Tiba di Jakarta, penerbangan domestik ke Batam.", "Tiba di Bandara Hang Nadim, pembagian air zamzam.", "Semoga Umroh yang mabrur. Aamiin."]},
        ],
        "published": True,
        "order": 1,
    },
    {
        "id": "umrah-vip",
        "name": "Umroh VIP",
        "fullTitle": "Umroh VIP Maret 2026 12 Hari [start Batam]",
        "subtitle": "Premium Bulan Maret 2026 - Program 12 Hari [start Batam]",
        "headline": "BATAM - SINGAPORE - JEDDAH | JEDDAH - SINGAPORE",
        "badge": "Premium",
        "badgeLong": "SAUDIA AIRLINES — HOTEL BINTANG 5",
        "duration": "12 Days",
        "durasi": "12 Hari",
        "tipePaket": "Umroh VIP",
        "departures": "Setiap minggu • Premium",
        "departureDate": "2026-03-15",
        "returnDate": "2026-03-26",
        "departureCity": "Batam",
        "availableSeats": 22,
        "priceFrom": "Rp 39,500,000",
        "airline": "Saudia / Emirates (Direct)",
        "hotelMakkah": "Hotel ★★★★★ — 50m from Masjidil Haram",
        "hotelMadinah": "Hotel ★★★★★ — 100m from Masjid Nabawi",
        "image": "https://images.pexels.com/photos/34498854/pexels-photo-34498854.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "gallery": [
            "https://images.pexels.com/photos/34498854/pexels-photo-34498854.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=900&w=1200",
            "https://images.unsplash.com/photo-1646228626691-862369e6a787?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
            "https://images.unsplash.com/photo-1575751639353-e292e76daca3?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
            "https://images.pexels.com/photos/33169789/pexels-photo-33169789.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=900&w=1200",
        ],
        "overview": "Paket Umroh VIP 12 hari menghadirkan pengalaman ibadah premium dengan akomodasi hotel bintang 5 yang sangat dekat dengan Masjidil Haram dan Masjid Nabawi. Penerbangan kelas premium, kuota terbatas, pelayanan personal.",
        "routes": ["Keberangkatan tanggal: 15 Maret 2026", "Kepulangan tanggal: 26 Maret 2026", "Penerbangan PP Singapore - Jeddah", "Termasuk PP Ferry Batam - Singapore", "Hotel Madinah Bintang 5 - Dar Al Iman Intercontinental", "Hotel Mekkah Bintang 5 - Pullman Zamzam", "Kuota terbatas, maks 25 jamaah per grup"],
        "bonuses": [
            {"title": "BONUS 1: Kereta Cepat Haramain", "desc": "Madinah ke Mekkah hanya 2 jam.", "image": "https://images.unsplash.com/photo-1581365365829-9c8a64a307c0?auto=format&fit=crop&w=600&q=80"},
            {"title": "BONUS 2: Welcome Dinner di Pullman", "desc": "Premium dining experience di Pullman Zamzam.", "image": "https://images.unsplash.com/photo-1668020024175-c1bca87c5a9d?auto=format&fit=crop&w=600&q=80"},
        ],
        "pembimbing": "Ustadz senior alumni Universitas Madinah dengan pendamping pribadi",
        "highlights": ["Hotel Bintang 5 view Ka'bah", "Penerbangan kelas premium direct", "Kuota terbatas", "Catering ala carte premium", "City tour dengan bus eksekutif", "Welcome dinner Pullman Zamzam"],
        "includes": ["Penerbangan langsung kelas bintang 5", "Hotel bintang 5 dekat haram", "Visa umroh resmi & express", "City tour Madinah & Makkah", "Pembimbing ulama berpengalaman", "Kuota terbatas, pelayanan personal", "Bagasi 40 kg + Zamzam 5L"],
        "excludes": ["Biaya paspor & vaksin", "Kelebihan bagasi", "Pengeluaran pribadi", "Tip muthawif (suggested)"],
        "terms": ["Paspor Asli minimal 7 bulan sebelum keberangkatan", "Pas Foto Background Putih 4x6", "Foto KTP & KK", "Foto Akta Lahir (anak)", "DP Rp 10.000.000 per orang", "Buku Vaksin Meningitis"],
        "hotels": [
            {"name": "Dar Al Iman Intercontinental", "rating": 5, "location": "Madinah", "description": "Hotel bintang 5 berjarak hanya 100m dari Masjid Nabawi.", "checkIn": "16 Maret 2026, 16:00", "checkOut": "20 Maret 2026, 13:00", "image": "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=800&q=80"},
            {"name": "Pullman Zamzam Tower", "rating": 5, "location": "Makkah", "description": "Hotel ikonik di Zamzam Tower, 50m dari Masjidil Haram.", "checkIn": "20 Maret 2026, 16:00", "checkOut": "25 Maret 2026, 13:00", "image": "https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&w=800&q=80"},
        ],
        "flights": [
            {"type": "Departure", "airline": "Saudia Airlines", "logo": "https://cdn.muslimpergi.com/uploads/airline/logo/1/medium_saudia.jpg", "from": {"code": "SIN", "name": "SINGAPORE CHANGI AIRPORT", "city": "Singapore, SG"}, "to": {"code": "JED", "name": "King Abdulaziz International Airport", "city": "Jeddah, SA"}, "departTime": "16 Maret 2026, 02:30", "arriveTime": "16 Maret 2026, 06:40"},
            {"type": "Arrival", "airline": "Saudia Airlines", "logo": "https://cdn.muslimpergi.com/uploads/airline/logo/1/medium_saudia.jpg", "from": {"code": "JED", "name": "King Abdulaziz International Airport", "city": "Jeddah, SA"}, "to": {"code": "SIN", "name": "SINGAPORE CHANGI AIRPORT", "city": "Singapore, SG"}, "departTime": "26 Maret 2026, 01:15", "arriveTime": "26 Maret 2026, 15:45"},
        ],
        "transports": [
            {"name": "Dallah Executive Bus", "logo": "https://cdn.muslimpergi.com/uploads/transport/logo/6/medium_dalah.jpg"},
            {"name": "Kereta Cepat Haramain", "logo": "https://cdn.muslimpergi.com/uploads/transport/logo/45/medium_kereta-cepat-mekkah-madinah.jpg"},
        ],
        "itinerary": [
            {"day": 1, "date": "15 Maret 2026", "dayName": "Ahad", "title": "BATAM - SINGAPORE", "meals": "Makan Malam (Kapal)", "activities": ["Berkumpul di Pelabuhan Batam Centre.", "Ferry SINDO ke HarbourFront Singapore.", "Bus eksekutif ke Changi Airport."]},
            {"day": 2, "date": "16 Maret 2026", "dayName": "Senin", "title": "SINGAPORE - JEDDAH - MADINAH", "meals": "Sarapan (Pesawat), Makan Siang (Bus), Makan Malam (Hotel)", "activities": ["Take-off Saudia Airlines menuju Jeddah.", "Perjalanan ke Madinah dengan bus eksekutif.", "Check-in Dar Al Iman Intercontinental."]},
            {"day": 3, "date": "17 Maret 2026", "dayName": "Selasa", "title": "MADINAH - WALKING TOUR", "meals": "Sarapan, Makan Siang, Makan Malam (Hotel)", "activities": ["Ziarah Makam Rasulullah SAW & Makam Baqi.", "Memperbanyak ibadah di Masjid Nabawi."]},
            {"day": 4, "date": "18 Maret 2026", "dayName": "Rabu", "title": "ZIARAH MADINAH", "meals": "Sarapan, Makan Siang, Makan Malam (Hotel)", "activities": ["Ziarah Masjid Quba, Jabal Uhud, Masjid Qiblatain.", "Ziarah Raudhah (sesuai tasreh)."]},
            {"day": 5, "date": "19 Maret 2026", "dayName": "Kamis", "title": "IBADAH MADINAH", "meals": "Sarapan, Makan Siang, Makan Malam (Hotel)", "activities": ["Hari bebas, memperbanyak ibadah dan ziarah."]},
            {"day": 6, "date": "20 Maret 2026", "dayName": "Jumat", "title": "MADINAH - MAKKAH", "meals": "Sarapan, Makan Siang, Makan Malam (Hotel)", "activities": ["Check-out, miqot di Bir Ali, Kereta Cepat Haramain.", "Check-in Pullman Zamzam.", "Umroh I."]},
            {"day": 7, "date": "21 Maret 2026", "dayName": "Sabtu", "title": "MAKKAH - CITY TOUR", "meals": "Sarapan, Makan Siang, Makan Malam (Hotel)", "activities": ["City tour: Jabal Tsur, Arafah, Muzdalifah, Mina.", "Miqot Tan'im untuk Umroh II."]},
            {"day": 8, "date": "22 Maret 2026", "dayName": "Ahad", "title": "MAKKAH - IBADAH", "meals": "Sarapan, Makan Siang, Makan Malam (Hotel)", "activities": ["Sholat berjamaah, welcome dinner premium."]},
            {"day": 9, "date": "23 Maret 2026", "dayName": "Senin", "title": "MAKKAH - KONSULTASI", "meals": "Sarapan, Makan Siang, Makan Malam (Hotel)", "activities": ["Konsultasi pribadi dengan ulama.", "Tawaf sunnah."]},
            {"day": 10, "date": "24 Maret 2026", "dayName": "Selasa", "title": "MAKKAH - FREE DAY", "meals": "Sarapan, Makan Siang, Makan Malam (Hotel)", "activities": ["Hari bebas — belanja, ibadah pribadi."]},
            {"day": 11, "date": "25 Maret 2026", "dayName": "Rabu", "title": "MAKKAH - JEDDAH", "meals": "Sarapan, Makan Siang (Bus), Makan Malam (Restoran)", "activities": ["Tawaf Wada', check-out.", "City tour Jeddah: Balad / Corniche.", "Makan malam, perjalanan ke bandara."]},
            {"day": 12, "date": "26 Maret 2026", "dayName": "Kamis", "title": "JEDDAH - SINGAPORE - BATAM", "meals": "Sarapan (Pesawat), Makan Malam (Kapal)", "activities": ["Penerbangan Saudia ke Singapore.", "Bus & Ferry ke Batam.", "Pembagian air zamzam."]},
        ],
        "published": True,
        "order": 2,
    },
    {
        "id": "umrah-plus",
        "name": "Umroh Plus Turki",
        "fullTitle": "Umroh Plus Turki Mei 2026 14 Hari [start Batam]",
        "subtitle": "Wisata Sejarah Islam — Program 14 Hari [start Batam]",
        "headline": "BATAM - SINGAPORE - ISTANBUL - JEDDAH | JEDDAH - ISTANBUL - SINGAPORE",
        "badge": "Wisata Sejarah",
        "badgeLong": "TURKISH AIRLINES — BONUS TOUR ISTANBUL",
        "duration": "14 Days",
        "durasi": "14 Hari",
        "tipePaket": "Umroh Plus",
        "departures": "Mar • May • Sep • Nov 2026",
        "departureDate": "2026-05-12",
        "returnDate": "2026-05-25",
        "departureCity": "Batam",
        "availableSeats": 25,
        "priceFrom": "Rp 45,000,000",
        "airline": "Turkish Airlines (Direct)",
        "hotelMakkah": "Hotel ★★★★★ — Pullman Zamzam area",
        "hotelMadinah": "Hotel ★★★★★ — Anwar Al Madinah",
        "image": "https://images.unsplash.com/photo-1592326871020-04f58c1a52f3?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDk1Nzd8MHwxfHNlYXJjaHwxfHxrYWFiYSUyMG1lY2NhfGVufDB8fHx8MTc4MDE4MjY2NHww&ixlib=rb-4.1.0&q=85",
        "gallery": [
            "https://images.unsplash.com/photo-1592326871020-04f58c1a52f3?crop=entropy&cs=srgb&fm=jpg&w=1200&q=80",
            "https://images.unsplash.com/photo-1527838832700-5059252407fa?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1668020024175-c1bca87c5a9d?auto=format&fit=crop&w=1200&q=80",
        ],
        "overview": "Umroh Plus Turki 14 hari menggabungkan ibadah suci di Tanah Suci dengan eksplorasi peradaban Islam di Istanbul.",
        "routes": ["Keberangkatan tanggal: 12 Mei 2026", "Kepulangan tanggal: 25 Mei 2026", "Penerbangan PP Turkish Airlines", "Termasuk PP Ferry Batam - Singapore", "8 hari Tanah Suci + 4 hari Istanbul", "Hotel bintang 5 di seluruh perjalanan", "Maks 25 jamaah per grup"],
        "bonuses": [
            {"title": "BONUS 1: Tour Istanbul 4 Hari", "desc": "Blue Mosque, Hagia Sophia, Topkapi, Grand Bazaar.", "image": "https://images.unsplash.com/photo-1527838832700-5059252407fa?auto=format&fit=crop&w=600&q=80"},
            {"title": "BONUS 2: Cruise Bosphorus & Dinner", "desc": "Cruise dengan makan malam khas Turki.", "image": "https://images.unsplash.com/photo-1668020024175-c1bca87c5a9d?auto=format&fit=crop&w=600&q=80"},
        ],
        "pembimbing": "Ustadz senior + Local Tour Guide berbahasa Indonesia di Istanbul",
        "highlights": ["8 hari Tanah Suci + 4 hari Istanbul", "Turkish Airlines direct flight", "Tour situs bersejarah Islam", "Cruise Bosphorus + dinner", "Hotel bintang 5", "Welcome dinner khas Turki"],
        "includes": ["Tour Istanbul: Blue Mosque, Hagia Sophia", "Hotel bintang 5 di seluruh perjalanan", "Penerbangan Turkish Airlines", "Pembimbing ibadah & city guide", "Cruise Bosphorus & makan eksklusif", "Limited 25 pax per group"],
        "excludes": ["Biaya paspor & vaksinasi", "Pengeluaran pribadi", "Tip city guide & muthawif"],
        "terms": ["Paspor Asli minimal 8 bulan", "Pas Foto Background Putih 4x6", "Foto KTP, KK, Akta Lahir", "DP Rp 7.500.000 per orang", "Buku Vaksin Meningitis"],
        "hotels": [
            {"name": "Qasr Al Ansar Golden Tulip", "rating": 5, "location": "Madinah", "description": "Hotel premium di Markaziah Madinah.", "checkIn": "14 Mei 2026, 16:00", "checkOut": "17 Mei 2026, 13:00", "image": "https://cdn.muslimpergi.com/uploads/hotel/photo/636/medium_qasr-al-ansar-new-palace.jpg"},
            {"name": "Royal Majestic Hotel Makkah", "rating": 5, "location": "Makkah", "description": "Hotel premium 4 menit ke Masjidil Haram.", "checkIn": "17 Mei 2026, 16:00", "checkOut": "21 Mei 2026, 13:00", "image": "https://cdn.muslimpergi.com/uploads/hotel/photo/175/medium_hotel-royal-majestic-makkah.jpg"},
            {"name": "Sultanahmet Boutique Hotel", "rating": 5, "location": "Istanbul", "description": "Hotel boutique di Sultanahmet, walking distance ke Blue Mosque.", "checkIn": "21 Mei 2026, 16:00", "checkOut": "24 Mei 2026, 12:00", "image": "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=800&q=80"},
        ],
        "flights": [
            {"type": "Departure", "airline": "Turkish Airlines", "logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Turkish_Airlines_logo_2019_compact.svg/2560px-Turkish_Airlines_logo_2019_compact.svg.png", "from": {"code": "SIN", "name": "SINGAPORE CHANGI AIRPORT", "city": "Singapore, SG"}, "to": {"code": "JED", "name": "King Abdulaziz International Airport", "city": "Jeddah, SA"}, "departTime": "13 Mei 2026, 23:50", "arriveTime": "14 Mei 2026, 08:20"},
            {"type": "Mid", "airline": "Turkish Airlines", "logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Turkish_Airlines_logo_2019_compact.svg/2560px-Turkish_Airlines_logo_2019_compact.svg.png", "from": {"code": "JED", "name": "King Abdulaziz International Airport", "city": "Jeddah, SA"}, "to": {"code": "IST", "name": "Istanbul Airport", "city": "Istanbul, TR"}, "departTime": "21 Mei 2026, 14:00", "arriveTime": "21 Mei 2026, 18:30"},
            {"type": "Arrival", "airline": "Turkish Airlines", "logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Turkish_Airlines_logo_2019_compact.svg/2560px-Turkish_Airlines_logo_2019_compact.svg.png", "from": {"code": "IST", "name": "Istanbul Airport", "city": "Istanbul, TR"}, "to": {"code": "SIN", "name": "SINGAPORE CHANGI AIRPORT", "city": "Singapore, SG"}, "departTime": "24 Mei 2026, 23:00", "arriveTime": "25 Mei 2026, 18:30"},
        ],
        "transports": [{"name": "Dallah Executive Bus", "logo": "https://cdn.muslimpergi.com/uploads/transport/logo/6/medium_dalah.jpg"}, {"name": "Kereta Cepat Haramain", "logo": "https://cdn.muslimpergi.com/uploads/transport/logo/45/medium_kereta-cepat-mekkah-madinah.jpg"}],
        "itinerary": [
            {"day": 1, "date": "12 Mei 2026", "dayName": "Selasa", "title": "BATAM - SINGAPORE", "meals": "Makan Malam (Kapal)", "activities": ["Berkumpul di Pelabuhan Batam Centre, Ferry ke HarbourFront.", "Bus ke Changi Airport."]},
            {"day": 2, "date": "13 Mei 2026", "dayName": "Rabu", "title": "SINGAPORE - JEDDAH", "meals": "Sarapan & Makan Siang (Pesawat)", "activities": ["Penerbangan Turkish Airlines via Istanbul."]},
            {"day": 3, "date": "14 Mei 2026", "dayName": "Kamis", "title": "JEDDAH - MADINAH", "meals": "Makan Siang (Bus), Malam (Hotel)", "activities": ["Tiba di Jeddah, perjalanan ke Madinah.", "Ibadah di Masjid Nabawi."]},
            {"day": 4, "date": "15 Mei 2026", "dayName": "Jumat", "title": "MADINAH - ZIARAH", "meals": "3x Sehari (Hotel)", "activities": ["Ziarah Makam Rasulullah, Masjid Quba, Jabal Uhud.", "Sholat Jumat di Masjid Nabawi."]},
            {"day": 5, "date": "16 Mei 2026", "dayName": "Sabtu", "title": "MADINAH", "meals": "3x Sehari (Hotel)", "activities": ["Memperbanyak ibadah, ziarah Raudhah."]},
            {"day": 6, "date": "17 Mei 2026", "dayName": "Ahad", "title": "MADINAH - MAKKAH", "meals": "3x Sehari (Hotel)", "activities": ["Miqot di Bir Ali, Kereta Cepat Haramain.", "Umroh I."]},
            {"day": 7, "date": "18 Mei 2026", "dayName": "Senin", "title": "MAKKAH - CITY TOUR", "meals": "3x Sehari (Hotel)", "activities": ["City tour Makkah, miqot Tan'im untuk Umroh II."]},
            {"day": 8, "date": "19 Mei 2026", "dayName": "Selasa", "title": "MAKKAH", "meals": "3x Sehari (Hotel)", "activities": ["Memperbanyak ibadah pribadi."]},
            {"day": 9, "date": "20 Mei 2026", "dayName": "Rabu", "title": "MAKKAH - FREE DAY", "meals": "3x Sehari (Hotel)", "activities": ["Hari bebas, belanja, ibadah."]},
            {"day": 10, "date": "21 Mei 2026", "dayName": "Kamis", "title": "MAKKAH - ISTANBUL", "meals": "Sarapan (Hotel), Makan Malam (Pesawat)", "activities": ["Tawaf Wada', check-out.", "Penerbangan ke Istanbul."]},
            {"day": 11, "date": "22 Mei 2026", "dayName": "Jumat", "title": "ISTANBUL - HERITAGE TOUR", "meals": "3x Sehari (Hotel)", "activities": ["Blue Mosque, Hagia Sophia, Topkapi, Grand Bazaar."]},
            {"day": 12, "date": "23 Mei 2026", "dayName": "Sabtu", "title": "ISTANBUL - BOSPHORUS", "meals": "Sarapan, Siang, Malam (Cruise)", "activities": ["Cruise Bosphorus + dinner.", "Spice Bazaar, Suleymaniye Mosque."]},
            {"day": 13, "date": "24 Mei 2026", "dayName": "Ahad", "title": "ISTANBUL - SINGAPORE", "meals": "Sarapan (Hotel), Malam (Pesawat)", "activities": ["Free time pagi, perjalanan ke bandara.", "Penerbangan ke Singapore."]},
            {"day": 14, "date": "25 Mei 2026", "dayName": "Senin", "title": "SINGAPORE - BATAM", "meals": "Sarapan (Pesawat)", "activities": ["Tiba di Changi, bus ke HarbourFront, ferry ke Batam.", "Tiba di Pelabuhan Batam Centre."]},
        ],
        "published": True,
        "order": 3,
    },
    {
        "id": "haji-khusus",
        "name": "Haji Khusus 2027",
        "fullTitle": "Haji Khusus 1448 H — Resmi Kemenag",
        "subtitle": "Kuota Haji Khusus 2027 — Program 26 Hari",
        "headline": "JAKARTA - JEDDAH | JEDDAH - JAKARTA (DIRECT)",
        "badge": "Resmi Kemenag",
        "badgeLong": "PIHK RESMI KEMENAG — SAUDIA AIRLINES",
        "duration": "26 Days",
        "durasi": "26 Hari",
        "tipePaket": "Haji Khusus",
        "departures": "Musim Haji 1448 H",
        "departureDate": "2027-05-20",
        "returnDate": "2027-06-14",
        "departureCity": "Jakarta",
        "availableSeats": 30,
        "priceFrom": "USD 13,500",
        "airline": "Saudia (Direct)",
        "hotelMakkah": "Hotel ★★★★★ — Zamzam Tower",
        "hotelMadinah": "Hotel ★★★★★ — Dar Al Iman Intercontinental",
        "image": "https://images.pexels.com/photos/29102893/pexels-photo-29102893.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "gallery": [
            "https://images.pexels.com/photos/29102893/pexels-photo-29102893.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=900&w=1200",
            "https://images.pexels.com/photos/34498854/pexels-photo-34498854.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=900&w=1200",
            "https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1200&q=80",
        ],
        "overview": "Paket Haji Khusus 26 hari dengan kuota resmi Kemenag RI. Bimbingan ulama intensif, akomodasi premium, tenda Mina & Arafah ber-AC.",
        "routes": ["Keberangkatan: 20 Mei 2027", "Kepulangan: 14 Juni 2027", "Penerbangan direct Saudia Airlines", "Hotel Madinah Bintang 5 - Dar Al Iman", "Hotel Makkah Bintang 5 - Zamzam Tower", "Tenda Mina & Arafah ber-AC", "Manasik intensif 6 bulan"],
        "bonuses": [{"title": "BONUS: Manasik Intensif 6 Bulan", "desc": "Bimbingan ibadah haji intensif oleh tim ulama berpengalaman.", "image": "https://images.unsplash.com/photo-1581365365829-9c8a64a307c0?auto=format&fit=crop&w=600&q=80"}],
        "pembimbing": "Tim ulama syariah berpengalaman (alumni Madinah & Al-Azhar)",
        "highlights": ["Kuota resmi Kemenag — Haji Khusus 2027", "Manasik intensif 6 bulan", "Tenda Mina & Arafah ber-AC + private", "Hotel Zamzam Tower & Dar Al Iman", "Catering Indonesia 3x sehari", "Asuransi komprehensif"],
        "includes": ["Kuota Haji Khusus resmi Kemenag", "Tenda Mina & Arafah AC khusus", "Catering Indonesia 3x sehari", "Bimbingan ulama syariah", "Manasik intensif 6 bulan", "Asuransi perjalanan komprehensif", "Bagasi 40 kg + Zamzam 5L"],
        "excludes": ["Vaksinasi meningitis", "Biaya tambahan dam bila dibutuhkan", "Pengeluaran pribadi"],
        "terms": ["Paspor Asli minimal 7 bulan sebelum keberangkatan", "Pas Foto Background Putih 4x6", "Foto KTP, KK, Akta Lahir", "Surat keterangan sehat dari dokter", "DP USD 5.000 per orang", "Buku Vaksin Meningitis", "Mengikuti seluruh sesi manasik wajib"],
        "hotels": [
            {"name": "Dar Al Iman Intercontinental", "rating": 5, "location": "Madinah", "description": "Hotel premium Madinah berjarak 100m dari Masjid Nabawi.", "checkIn": "21 Mei 2027, 16:00", "checkOut": "29 Mei 2027, 13:00", "image": "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80"},
            {"name": "Zamzam Tower (Pullman ZamZam)", "rating": 5, "location": "Makkah", "description": "Hotel ikonik langsung menghadap Masjidil Haram.", "checkIn": "29 Mei 2027, 16:00", "checkOut": "10 Juni 2027, 13:00", "image": "https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=800&q=80"},
        ],
        "flights": [
            {"type": "Departure", "airline": "Saudia Airlines", "logo": "https://cdn.muslimpergi.com/uploads/airline/logo/1/medium_saudia.jpg", "from": {"code": "CGK", "name": "Soekarno-Hatta International Airport", "city": "Jakarta, ID"}, "to": {"code": "JED", "name": "King Abdulaziz International Airport", "city": "Jeddah, SA"}, "departTime": "20 Mei 2027, 22:30", "arriveTime": "21 Mei 2027, 06:40"},
            {"type": "Arrival", "airline": "Saudia Airlines", "logo": "https://cdn.muslimpergi.com/uploads/airline/logo/1/medium_saudia.jpg", "from": {"code": "JED", "name": "King Abdulaziz International Airport", "city": "Jeddah, SA"}, "to": {"code": "CGK", "name": "Soekarno-Hatta International Airport", "city": "Jakarta, ID"}, "departTime": "14 Juni 2027, 01:15", "arriveTime": "14 Juni 2027, 17:45"},
        ],
        "transports": [{"name": "Dallah Executive Bus", "logo": "https://cdn.muslimpergi.com/uploads/transport/logo/6/medium_dalah.jpg"}, {"name": "Kereta Cepat Haramain", "logo": "https://cdn.muslimpergi.com/uploads/transport/logo/45/medium_kereta-cepat-mekkah-madinah.jpg"}],
        "itinerary": [
            {"day": "1-3", "date": "20-22 Mei 2027", "dayName": "—", "title": "BERANGKAT & TIBA DI MADINAH", "meals": "3x sehari (Hotel)", "activities": ["Berangkat ke Madinah via Saudia direct.", "Persiapan ibadah di Masjid Nabawi."]},
            {"day": "4-7", "date": "23-26 Mei 2027", "dayName": "—", "title": "ZIARAH MADINAH", "meals": "3x sehari (Hotel)", "activities": ["Raudhah, makam Rasulullah, ziarah situs sejarah."]},
            {"day": 8, "date": "27 Mei 2027", "dayName": "Kamis", "title": "BERANGKAT KE MAKKAH", "meals": "3x sehari (Hotel)", "activities": ["Ihram dari Bir Ali, perjalanan ke Makkah, umroh haji."]},
            {"day": "9-12", "date": "28-31 Mei 2027", "dayName": "—", "title": "PERSIAPAN WUKUF", "meals": "3x sehari (Hotel)", "activities": ["Ibadah intensif di Masjidil Haram, briefing manasik final."]},
            {"day": 13, "date": "1 Juni 2027", "dayName": "Selasa", "title": "TARWIYAH KE MINA", "meals": "3x sehari (Tenda Mina)", "activities": ["Bermalam di Mina, persiapan wukuf di Arafah."]},
            {"day": 14, "date": "2 Juni 2027", "dayName": "Rabu", "title": "WUKUF DI ARAFAH", "meals": "3x sehari (Tenda Arafah)", "activities": ["Puncak ibadah haji — wukuf di Padang Arafah."]},
            {"day": "15-17", "date": "3-5 Juni 2027", "dayName": "—", "title": "MABIT & LEMPAR JUMRAH", "meals": "3x sehari (Tenda)", "activities": ["Muzdalifah, mabit di Mina, lempar jumrah."]},
            {"day": "18-21", "date": "6-9 Juni 2027", "dayName": "—", "title": "TAWAF IFADHAH", "meals": "3x sehari (Hotel)", "activities": ["Tawaf ifadhah & sai haji, lempar jumrah tasyriq."]},
            {"day": "22-25", "date": "10-13 Juni 2027", "dayName": "—", "title": "IBADAH AKHIR MAKKAH", "meals": "3x sehari (Hotel)", "activities": ["Memperbanyak tawaf, ziarah Ja'ranah."]},
            {"day": 26, "date": "14 Juni 2027", "dayName": "Senin", "title": "TAWAF WADA' & PULANG", "meals": "Sarapan (Hotel), Makan Malam (Pesawat)", "activities": ["Tawaf perpisahan, perjalanan ke Jeddah, penerbangan pulang."]},
        ],
        "published": True,
        "order": 4,
    },
]
